### ISSUE TITLE
Update externals

### ISSUE THREAD

**Issue by pdeiml** [ntim/famous#2]
Hi,

I had cloned the repository and I had compiled it. Everything fine.
Then I had run the executable ./fresnelSim/fresnelSim and this error occurred:
```
*************************************************************
 Geant4 version Name: geant4-10-03-patch-02    (27-July-2017)
                      Copyright : Geant4 Collaboration
                      Reference : NIM A 506 (2003), 250-303
                            WWW : http://cern.ch/geant4
*************************************************************

G4SipmUiMessenger::initRandomEngine(): CLHEP::MTwistEngine with seed 1515659469963456

-------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : em0001
      issued by : G4EmSaturation::InitialiseBirksCoefficient
both electron and proton should exist
*** Fatal Exception *** core dump ***
-------- EEEE -------- G4Exception-END --------- EEEE -------


*** G4Exception: Aborting execution ***
```

Which is linked to that issue:
https://github.com/ntim/g4sipm/issues/1

Hence, I had went into the folder `/externals/g4sipm`, did a `git update origin master`, recompiled everything and now it works.

To sum up, you should change here
https://github.com/ntim/famous/tree/master/externals
this `g4sipm @ 32d12fcf3d01894dc9cf4e4c7ba1a7ec056e8fd6` to
`g4sipm @ 40b0017f266c0708c39c595ebb4d09385acc2717`.

**Comment by ntim** [comment]
Thanks for the tip
